# Generated by Django 3.1.7 on 2021-03-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(blank=True, upload_to='static/images/products')),
                ('product_title', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
            ],
        ),
    ]
